'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { LifecycleActionButton } from './_components/LifecycleActionButton';
import { ShareAssessmentButton } from '../_components/ShareAssessmentButton';

type Assessment = {
  id:string; title:string; description:string; status:string; duration_seconds:number; starts_at:number|null; ends_at:number|null;
  registration_ends_at:number|null; question_count:number; total_marks:number; registration_count:number; started_count:number; submitted_count:number;
  paper_version:number; version:number;
};

const statusLabel:Record<string,string>={draft:'Draft',registration_open:'Registrations open',registration_closed:'Registrations closed',scheduled:'Scheduled',live:'Test live',ended:'Test ended',results_processing:'Processing results',results_ready:'Results ready',results_released:'Results released',archived:'Archived'};
const formatDate=(epoch:number|null)=>epoch?new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kolkata'}).format(new Date(epoch*1000)):'Not set';
const resultsCopy=(assessment:Assessment)=>assessment.status==='results_released'?'Candidate reports are visible':assessment.status==='results_ready'?'Review complete · ready to publish':assessment.status==='results_processing'?'Review ranks, exclusions and question analytics':assessment.status==='ended'?`${assessment.submitted_count} submissions ready to compute`:assessment.status==='live'?'End the test to begin result processing':'Available after the test ends';
const resultsAction=(status:string)=>status==='results_released'?'Manage results':status==='results_ready'?'Publish results':status==='results_processing'?'Review results':status==='ended'?'Compute results':'Open results';

export function OrganizerDashboard() {
  const [assessments,setAssessments]=useState<Assessment[]>([]); const [selectedId,setSelectedId]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch('/api/assessments',{cache:'no-store'});const payload=await response.json() as {assessments?:Assessment[];error?:string};if(!response.ok)throw new Error(payload.error||'Could not load assessments.');setAssessments(payload.assessments||[]);setSelectedId((current)=>current||(payload.assessments?.[0]?.id||''));}catch(reason){setError(reason instanceof Error?reason.message:'Could not load assessments.');}finally{setLoading(false);}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  const selected=useMemo(()=>assessments.find((item)=>item.id===selectedId)||assessments[0],[assessments,selectedId]);
  const checks=selected?[['Assessment details',Boolean(selected.title&&selected.starts_at&&selected.ends_at)],['Validated question paper',selected.question_count>0],['Positive total marks',selected.total_marks>0],['Registration window',Boolean(selected.registration_ends_at)],['Google sign-in','ready'] as const]:[];
  const ready=checks.filter((check)=>Boolean(check[1])).length;

  if(loading)return <div className="admin-content"><div className="organizer-loading"><strong>Loading organizer workspace…</strong><span>Reading the current assessment lifecycle and paper versions.</span></div></div>;
  if(error)return <div className="admin-content"><div className="organizer-empty"><h2>Workspace could not load</h2><p>{error}</p><button className="solid-action small" onClick={()=>void load()}>Retry</button></div></div>;
  if(!selected)return <div className="admin-content"><section className="organizer-empty"><p className="page-label">Your first assessment</p><h2>Create the test, then publish its question paper.</h2><p>The organizer workflow will guide you through timings, rules, CSV validation and registration readiness.</p><a className="solid-action" href="/organizer/new">Create the first test →</a></section></div>;

  const canSchedule=['draft','registration_open','registration_closed'].includes(selected.status)&&selected.question_count>0;
  return <div className="admin-content">
    <section className="organizer-command"><div><p className="page-label">Selected assessment · Paper v{selected.paper_version}</p><h2>{selected.title}</h2><p>{formatDate(selected.starts_at)} · {Math.round(selected.duration_seconds/60)} minutes · {selected.question_count} questions · {selected.total_marks} marks</p></div><div className="command-actions"><div className="command-status"><span className="live-dot"/><div><small>Current stage</small><strong>{statusLabel[selected.status]||selected.status}</strong></div></div>{selected.status==='draft'?<span className="share-unavailable">Publish the schedule to create a candidate link.</span>:<ShareAssessmentButton assessmentId={selected.id} title={selected.title} label="Share candidate link" className="organizer-share-button"/>}</div></section>
    <section className="assessment-switcher" aria-label="Assessment selector"><label>Working on<select value={selected.id} onChange={(event)=>setSelectedId(event.target.value)}>{assessments.map((item)=><option key={item.id} value={item.id}>{item.title} · {statusLabel[item.status]||item.status}</option>)}</select></label><span>{assessments.length} assessment{assessments.length===1?'':'s'} in workspace</span></section>
    <section className="organizer-shortcuts" aria-label="Common organizer tasks">
      <a className="primary" href="/organizer/new"><span>01</span><strong>Create another test</strong><small>Start with recommended OA defaults</small></a>
      <a href={`/organizer/assessment?assessment=${encodeURIComponent(selected.id)}`}><span>02</span><strong>Edit assessment</strong><small>Window, duration and integrity rules</small></a>
      <a href={`/organizer/questions?assessment=${encodeURIComponent(selected.id)}`}><span>03</span><strong>{selected.question_count?'Replace':'Upload'} question paper</strong><small>Validated CSV plus image ZIP</small></a>
      <a href="/organizer/participants"><span>04</span><strong>Manage registrations</strong><small>{selected.registration_count} candidates currently registered</small></a>
    </section>
    <section className="lifecycle-panel"><div className="panel-heading"><div><p className="page-label">Controlled lifecycle</p><h2>Move forward only when the test is ready</h2></div><span>Every change is versioned and audited</span></div><div className="lifecycle-steps">
      <article className="complete"><span>01</span><div><strong>Test details</strong><small>Version {selected.version} · timings and rules saved</small></div><a href={`/organizer/assessment?assessment=${encodeURIComponent(selected.id)}`}>Review</a></article>
      <article className={selected.question_count?'complete':'current'}><span>02</span><div><strong>Question paper</strong><small>{selected.question_count?`${selected.question_count} questions · ${selected.total_marks} marks`:'Upload required before registration'}</small></div><a href={`/organizer/questions?assessment=${encodeURIComponent(selected.id)}`}>{selected.question_count?'Review':'Upload'}</a></article>
      <article className={['scheduled','live'].includes(selected.status)?'current':''}><span>03</span><div><strong>Publish schedule</strong><small>{canSchedule?'One approval activates the registration and test timestamps':`${selected.registration_count} registered · windows run automatically`}</small></div>{canSchedule?<LifecycleActionButton assessmentId={selected.id} action="schedule_test" label="Publish schedule" disabled={!canSchedule} onDone={()=>void load()}/>:<a href={`/organizer/assessment?assessment=${encodeURIComponent(selected.id)}#window`}>Edit window</a>}</article>
      <article className={selected.status==='live'?'current':selected.status==='ended'?'complete':''}><span>04</span><div><strong>Conduct test</strong><small>{selected.status==='live'?`${selected.started_count} started · ${selected.submitted_count} submitted`:selected.status==='scheduled'?'Starts and closes automatically from the published window':selected.status==='ended'?'Window closed automatically':'Publish the schedule first'}</small></div>{selected.status==='live'?<LifecycleActionButton assessmentId={selected.id} action="end_test" label="End early" tone="danger" onDone={()=>void load()}/>:<a href={`/organizer/assessment?assessment=${encodeURIComponent(selected.id)}#window`}>View timing</a>}</article>
      <article className={selected.status==='ended'||selected.status.startsWith('results_')?'current':''}><span>05</span><div><strong>Results</strong><small>{resultsCopy(selected)}</small></div><a href="/organizer/results">{resultsAction(selected.status)}</a></article>
    </div></section>
    <section className="admin-metrics" aria-label="Assessment metrics"><div><span>Questions</span><strong>{selected.question_count}</strong><small>paper version {selected.paper_version}</small></div><div><span>Total marks</span><strong>{selected.total_marks}</strong><small>derived from uploaded paper</small></div><div><span>Registrations</span><strong>{selected.registration_count}</strong><small>database-backed count</small></div><div><span>Submitted</span><strong>{selected.submitted_count}</strong><small>{selected.started_count} attempts started</small></div></section>
    <section className="admin-dashboard-grid"><article className="assessment-ledger"><div className="panel-heading"><div><p className="page-label">Assessment portfolio</p><h2>All tests</h2></div><a href="/organizer/new">New test →</a></div><div className="ledger-table"><div className="ledger-row head"><span>Assessment</span><span>Status</span><span>Paper</span><span>Starts</span></div>{assessments.map((item)=><button className={`ledger-row ${item.id===selected.id?'selected':''}`} key={item.id} onClick={()=>setSelectedId(item.id)}><strong>{item.title}</strong><span>{statusLabel[item.status]||item.status}</span><span>{item.question_count} Q · {item.total_marks} M</span><span>{formatDate(item.starts_at)}</span></button>)}</div></article><aside className="readiness-panel"><p className="page-label">Pre-flight checklist</p><h2>{ready} of {checks.length} checks passed</h2><ul>{checks.map(([label,passed])=><li className={passed?'done':'pending'} key={String(label)}>{label}</li>)}</ul><a href={`/organizer/assessment?assessment=${encodeURIComponent(selected.id)}`}>Resolve assessment setup →</a></aside></section>
  </div>;
}
