'use client';import { useEffect,useMemo,useState } from 'react';
type Assessment={id:string;title:string};type Registration={id:string;email:string;name:string;college:string;graduation_year:number;branch:string;status:string;registered_at:number;attempt_status:string|null;score:number|null;max_score:number|null;answered_count:number|null;tab_switches:number|null;submitted_at:number|null};
const neutral=(value:unknown)=>{const text=String(value??'');return /^[=+\-@]/.test(text)?`'${text}`:text;};
export function ParticipantsManager(){const [assessments,setAssessments]=useState<Assessment[]>([]),[selected,setSelected]=useState(''),[rows,setRows]=useState<Registration[]>([]),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[message,setMessage]=useState('');
 useEffect(()=>{void fetch('/api/assessments').then(async(r)=>await r.json() as {assessments?:Assessment[]}).then((data)=>{setAssessments(data.assessments||[]);setSelected(data.assessments?.[0]?.id||'');});},[]);useEffect(()=>{if(!selected)return;void fetch(`/api/registrations?assessmentId=${encodeURIComponent(selected)}`,{cache:'no-store'}).then(async(r)=>await r.json() as {registrations?:Registration[]}).then((data)=>setRows(data.registrations||[]));},[selected]);
 const visible=useMemo(()=>rows.filter((row)=>(status==='all'||row.status===status)&&`${row.name} ${row.email} ${row.college} ${row.branch}`.toLowerCase().includes(query.toLowerCase())),[rows,query,status]);const summary={registered:rows.filter((r)=>r.status==='registered').length,started:rows.filter((r)=>r.status==='started').length,submitted:rows.filter((r)=>r.status==='submitted').length,blocked:rows.filter((r)=>r.status==='blocked').length};
 async function change(row:Registration){const action=row.status==='blocked'?'unblock':'block';const response=await fetch('/api/registrations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,registrationId:row.id})});if(response.ok){setRows(rows.map((item)=>item.id===row.id?{...item,status:action==='block'?'blocked':'registered'}:item));setMessage(`${row.email} ${action==='block'?'blocked':'restored'}.`);}}
 function exportCsv(){const headers=['Name','Email','College','Graduation year','Branch','Registration status','Attempt status','Score','Maximum score','Answered','Tab switches','Submitted at'];const lines=[headers,...visible.map((r)=>[r.name,r.email,r.college,r.graduation_year,r.branch,r.status,r.attempt_status||'',r.score??'',r.max_score??'',r.answered_count??'',r.tab_switches??'',r.submitted_at?new Date(r.submitted_at*1000).toISOString():''])].map((row)=>row.map((item)=>`"${neutral(item).replaceAll('"','""')}"`).join(','));const blob=new Blob([lines.join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='c-and-assess-participants.csv';link.click();URL.revokeObjectURL(url);}
 return <section className="participants-manager"><div className="participant-toolbar"><label>Assessment<select value={selected} onChange={(e)=>setSelected(e.target.value)}>{assessments.map((item)=><option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label>Search<input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Name, email, college or branch"/></label><label>Status<select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="registered">Registered</option><option value="started">Started</option><option value="submitted">Submitted</option><option value="blocked">Blocked</option></select></label><button className="outline-action" onClick={exportCsv} disabled={!visible.length}>Export CSV</button></div><div className="participant-summary"><article><span>Registered</span><strong>{summary.registered}</strong></article><article><span>In progress</span><strong>{summary.started}</strong></article><article><span>Submitted</span><strong>{summary.submitted}</strong></article><article><span>Blocked</span><strong>{summary.blocked}</strong></article></div>{message&&<p className="catalog-message">{message}</p>}<div className="participant-table-wrap"><table className="participant-table"><thead><tr><th>Candidate</th><th>College</th><th>Status</th><th>Score</th><th>Integrity</th><th>Action</th></tr></thead><tbody>{visible.map((row)=><tr key={row.id}><td><strong>{row.name}</strong><span>{row.email}</span></td><td><strong>{row.college}</strong><span>{row.branch} · {row.graduation_year}</span></td><td><span className={`status-chip ${row.status}`}>{row.attempt_status||row.status}</span></td><td>{row.score===null?'—':`${row.score} / ${row.max_score}`}</td><td>{row.tab_switches??0} tab switches</td><td><button className="table-action" onClick={()=>void change(row)}>{row.status==='blocked'?'Unblock':'Block'}</button></td></tr>)}</tbody></table>{!visible.length&&<div className="catalog-empty">No candidates match this view.</div>}</div></section>;
}
