import { env } from 'cloudflare:workers';import { getRequestSession } from '../../../../lib/auth';import { jsonAnswers,jsonNumberMap } from '../../../../lib/candidate-store';import { scoreAttempt,ScoreQuestion } from '../../../../lib/scoring';import { ensureResultSchema } from '../../../../lib/result-store';import { protectMutation } from '../../../../lib/request-security';
type Body={attemptId?:string;answers?:Record<string,string[]>;marked?:string[];timeSpent?:Record<string,number>;tabSwitches?:number};
export async function POST(request:Request){
  const blocked=protectMutation(request,{scope:'attempt-submit',limit:8});if(blocked)return blocked;
  const user=await getRequestSession(request);if(!user)return Response.json({error:'Sign in required.'},{status:401});await ensureResultSchema();const body=await request.json() as Body;if(!body.attemptId)return Response.json({error:'Attempt is required.'},{status:400});
  const attempt=await env.DB.prepare(`SELECT t.*,a.status AS assessment_status FROM attempts t JOIN assessments a ON a.id=t.assessment_id WHERE t.id=? AND t.user_id=?`).bind(body.attemptId,user.sub).first<Record<string,unknown>>();if(!attempt)return Response.json({error:'Attempt not found.'},{status:404});const released=attempt.assessment_status==='results_released';if(attempt.status==='submitted'||attempt.status==='evaluated')return Response.json({submitted:true,submittedAt:attempt.submitted_at,score:released?attempt.score:null,maxScore:released?attempt.max_score:null,resultsReleased:released});
  const rows=await env.DB.prepare('SELECT id,type,answers_json,accepted_variants_json,tita_tolerance,marks,negative_marks FROM questions WHERE assessment_id=? AND is_active=1 ORDER BY position').bind(attempt.assessment_id).all<ScoreQuestion>();const allowed=new Set(rows.results.map((q)=>q.id));const now=Math.floor(Date.now()/1000);const expired=now>=Number(attempt.expires_at);const source=body.answers===undefined||expired?jsonAnswers(attempt.answers_json):body.answers;const answers=Object.fromEntries(Object.entries(source).filter(([id])=>allowed.has(id)).map(([id,values])=>[id,(Array.isArray(values)?values:[]).map(String).map((v)=>v.slice(0,4000)).slice(0,20)]));const marked=[...new Set((body.marked||[]).map(String).filter((id)=>allowed.has(id)))];const rawTimes=expired?jsonNumberMap(attempt.time_spent_json):(body.timeSpent||{});const timeSpent=Object.fromEntries(Object.entries(rawTimes).filter(([id])=>allowed.has(id)).map(([id,value])=>[id,Math.max(0,Math.min(86400,Math.floor(Number(value)||0)))]));const result=scoreAttempt(rows.results,answers);const details=Object.fromEntries(Object.entries(result.details).map(([id,detail])=>[id,{...detail,timeSeconds:Number(timeSpent[id]||0)}]));const tabSwitches=Math.max(Number(attempt.tab_switches||0),Math.min(1000,Number(body.tabSwitches||0)));
  const update=await env.DB.prepare(`UPDATE attempts SET status='submitted',answers_json=?,marked_json=?,time_spent_json=?,answered_count=?,tab_switches=?,result_json=?,score=?,max_score=?,correct_count=?,incorrect_count=?,unattempted_count=?,submitted_at=?,scored_at=?,updated_at=? WHERE id=? AND user_id=? AND status='started'`).bind(JSON.stringify(answers),JSON.stringify(marked),JSON.stringify(timeSpent),Object.values(answers).filter((value)=>value.some(Boolean)).length,tabSwitches,JSON.stringify(details),result.score,result.maxScore,result.correct,result.incorrect,result.unattempted,now,now,now,body.attemptId,user.sub).run();
  if(!update.meta.changes)return Response.json({error:'The attempt changed while it was being submitted. Refresh to see its status.'},{status:409});
  await env.DB.batch([env.DB.prepare("UPDATE registrations SET status='submitted',updated_at=? WHERE assessment_id=? AND user_id=?").bind(now,attempt.assessment_id,user.sub),env.DB.prepare("INSERT INTO proctor_events (id,attempt_id,event_type,detail_json,occurred_at) VALUES (?,?,'submitted',?,?)").bind(crypto.randomUUID(),body.attemptId,JSON.stringify({answered:Object.keys(answers).length,tabSwitches}),now)]);
  return Response.json({submitted:true,submittedAt:now,score:released?result.score:null,maxScore:released?result.maxScore:null,resultsReleased:released});
}
