import {mkdir,writeFile} from 'node:fs/promises';
import {dirname,resolve} from 'node:path';

const candidates=Number(process.argv[2]||200),assessmentId=process.argv[3]||`load-${candidates}`,output=resolve(process.argv[4]||'outputs/load-seed.sql');
const now=Math.floor(Date.now()/1000),quote=(value)=>`'${String(value).replaceAll("'","''")}'`;
const statements=[
  `INSERT INTO assessments (id,slug,title,description,status,duration_seconds,registration_starts_at,registration_ends_at,starts_at,ends_at,settings_json,version,paper_version,question_count,total_marks,published_at,created_by,created_at,updated_at) VALUES (${quote(assessmentId)},${quote(assessmentId)},'Load rehearsal','Non-production local rehearsal','live',3600,${now-3600},${now+7200},${now-60},${now+7200},${quote(JSON.stringify({shuffleQuestions:true,shuffleOptions:true,allowEditing:true,maxTabSwitches:3,startPolicy:'common_deadline',resultVisibility:'manual_release',solutionVisibility:'separate_release',tieBreaker:'shorter_time',audience:'open',allowedDomains:[],registrationCapacity:null,solutionsReleased:false}))},1,1,60,180,${now},'load-test',${now},${now});`,
];
for(let q=1;q<=60;q+=1)statements.push(`INSERT INTO questions (id,assessment_id,position,type,prompt,section_id,passage,options_json,answers_json,solution,marks,negative_marks,answer_keywords_json,keyword_marks,image_key,duration_seconds,tag,topic,subtopic,source,accepted_variants_json,tita_tolerance,difficulty,is_active,created_at,updated_at) VALUES (${quote(`${assessmentId}-q-${q}`)},${quote(assessmentId)},${q},'mcq',${quote(`Load question ${q}`)},NULL,'','["A","B","C","D"]','["A"]','Verified load-test solution',3,1,'[]',0,NULL,NULL,'Load','Load','', 'Synthetic','[]',NULL,'medium',1,${now},${now});`);
for(let i=0;i<candidates;i+=1){const user=`load-user-${candidates}-${i}`;statements.push(`INSERT INTO registrations (id,assessment_id,user_id,email,name,college,graduation_year,branch,status,consent_at,profile_json,blocked_reason,registered_at,updated_at) VALUES (${quote(crypto.randomUUID())},${quote(assessmentId)},${quote(user)},${quote(`${user}@example.test`)},${quote(`Load Candidate ${i}`)},'Synthetic College',2027,'Testing','registered',${now},'{}',NULL,${now},${now});`);}
await mkdir(dirname(output),{recursive:true});await writeFile(output,statements.join('\n'),'utf8');console.log(JSON.stringify({output,candidates,assessmentId,statements:statements.length}));
