import { env } from 'cloudflare:workers';import { getRequestSession } from '../../../../lib/auth';import { ensureResultSchema } from '../../../../lib/result-store';import { protectMutation } from '../../../../lib/request-security';
type Body={attemptId?:string;baseVersion?:number;answers?:Record<string,string[]>;marked?:string[];timeSpent?:Record<string,number>;tabSwitches?:number;event?:string};
const compact=(answers:Record<string,string[]>|undefined,allowed:Set<string>)=>Object.fromEntries(Object.entries(answers||{}).filter(([id])=>allowed.has(id)).map(([id,values])=>[id,(Array.isArray(values)?values:[]).map(String).map((v)=>v.slice(0,4000)).slice(0,20)]));
export async function POST(request:Request){
  const blocked=protectMutation(request,{scope:'attempt-save',limit:30});if(blocked)return blocked;
  const user=await getRequestSession(request);if(!user)return Response.json({error:'Sign in required.'},{status:401});await ensureResultSchema();const body=await request.json() as Body;if(!body.attemptId)return Response.json({error:'Attempt is required.'},{status:400});
  const attempt=await env.DB.prepare('SELECT id,assessment_id,status,answer_version,tab_switches,expires_at FROM attempts WHERE id=? AND user_id=?').bind(body.attemptId,user.sub).first<{id:string;assessment_id:string;status:string;answer_version:number;tab_switches:number;expires_at:number}>();if(!attempt)return Response.json({error:'Attempt not found.'},{status:404});if(attempt.status!=='started')return Response.json({error:'This attempt is no longer editable.',status:attempt.status},{status:409});
  const now=Math.floor(Date.now()/1000);if(now>=attempt.expires_at)return Response.json({error:'The attempt time has ended. Submit to finalize the last server checkpoint.'},{status:409});const ids=await env.DB.prepare('SELECT id FROM questions WHERE assessment_id=? AND is_active=1').bind(attempt.assessment_id).all<{id:string}>();const allowed=new Set(ids.results.map((q)=>q.id));const answers=compact(body.answers,allowed);const marked=[...new Set((body.marked||[]).map(String).filter((id)=>allowed.has(id)))];const tabSwitches=Math.max(attempt.tab_switches,Math.min(1000,Number(body.tabSwitches||0)));
  const timeSpent=Object.fromEntries(Object.entries(body.timeSpent||{}).filter(([id])=>allowed.has(id)).map(([id,value])=>[id,Math.max(0,Math.min(86400,Math.floor(Number(value)||0)))]));
  const result=await env.DB.prepare(`UPDATE attempts SET answers_json=?,marked_json=?,time_spent_json=?,answered_count=?,tab_switches=?,answer_version=answer_version+1,last_checkpoint_at=?,updated_at=? WHERE id=? AND user_id=? AND status='started' AND answer_version=?`).bind(JSON.stringify(answers),JSON.stringify(marked),JSON.stringify(timeSpent),Object.values(answers).filter((value)=>value.some(Boolean)).length,tabSwitches,now,now,body.attemptId,user.sub,Number(body.baseVersion||0)).run();
  if(!result.meta.changes){const current=await env.DB.prepare('SELECT answers_json,marked_json,answer_version,tab_switches FROM attempts WHERE id=?').bind(body.attemptId).first();return Response.json({error:'A newer checkpoint exists.',checkpoint:current},{status:409});}
  if(body.event)await env.DB.prepare('INSERT INTO proctor_events (id,attempt_id,event_type,detail_json,occurred_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),body.attemptId,String(body.event).slice(0,60),JSON.stringify({tabSwitches}),now).run();
  return Response.json({saved:true,answerVersion:Number(body.baseVersion||0)+1,serverNow:now});
}
